#!/bin/sh
if [ `ps -ef 2>&1 |grep -v grep|grep opkg|grep -c remove` -ge 1 ] || [ `ps -l 2>&1 |grep -v grep|grep opkg|grep -c remove` -ge 1 ];then
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/GREG-FHD-Aktualizacja 2 > /dev/null
  if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
    echo ""
    echo " Przeładuj teraz GUI!"
    echo ""
  else
    echo ""
    echo " You should restart GUI!"
    echo ""
  fi
fi
exit 0
