#!/bin/sh
if [ `ps -ef 2>&1 |grep -v grep|grep opkg|grep -c remove` -ge 1 ] || [ `ps -l 2>&1 |grep -v grep|grep opkg|grep -c remove` -ge 1 ];then
  rm -rf /usr/share/enigma2/GREGORY_FHD_GOLD 2 > /dev/null
  if `grep -q 'osd.language=pl_PL' </etc/enigma2/settings`; then
    echo ""
    echo "Skin skasowany. Przeładuj teraz GUI!"
    echo ""
  else
    echo ""
    echo "Skin removed. You should restart GUI!"
    echo ""
  fi
fi
exit 0
